swagger: '2.0'
info:
  version: '2.0'
  title: "Nexmo Applications API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions
paths:
  /applications:
    get:
      description: Get details of all apps associated with an account.
      operationId: GET_applications
      parameters:
        - description: |-

            Start date range in ISO-8601 UTC format YYYY-MM-DDTHH:MM:SSZ
          in: query
          name: date_start
          type: string
        - default: false
          description: >-

            Option to only return the record count. Options are ‘true’ or
            ‘false’. Defaults to false.
          in: query
          name: count
          type: boolean
        - default: 10
          description: The number of records to limit the response to.
          in: query
          name: page_size
          type: number
        - default: 0
          description: 'Offset of the first record. '
          in: query
          name: page_offset
          type: number
        - description: 'End date range in ISO-8601 UTC format YYYY-MM-DDTHH:MM:SSZ'
          in: query
          name: date_end
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              _embedded:
                applications:
                  - _links:
                      numberpool:
                        href: /numberpools/10
                      self:
                        href: /applications/63f61863-4a51-4f6b-86e1-46edebcf9356
                    answer_method: GET
                    answer_url: 'http://myanswerurl.com'
                    application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
                    application_type: voice
                    backup_method: GET
                    backup_url: 'http://mybackupurll.com'
                    event_method: GET
                    event_url: 'http://myeventurl.com'
                    name: Nexmo-conference
                    numberpool_id: '10'
              _links:
                first:
                  href: /applications
                last:
                  href: /applications?page_offset=50
                next:
                  href: /applications?page_offset=20
                prev:
                  href: /applications
                self:
                  href: /applications?page_offset=10
              count: '1020'
              page_offset: '150'
              page_size: '50'
          schema:
            allOf:
              - properties:
                  _embedded:
                    properties:
                      applications:
                        items:
                          $ref: '#/definitions/applicationResponse'
                        type: array
                    type: object
                  _links:
                    properties:
                      first:
                        properties:
                          href:
                            type: string
                        type: object
                      last:
                        properties:
                          href:
                            type: string
                        type: object
                      next:
                        properties:
                          href:
                            type: string
                        type: object
                      prev:
                        properties:
                          href:
                            type: string
                        type: object
                      self:
                        properties:
                          href:
                            type: string
                        type: object
                    type: object
                  count:
                    type: string
                  page_offset:
                    type: string
                  page_size:
                    type: string
                type: object
      summary: List Applications
      tags:
        - Application
    post:
      consumes:
        - application/x-www-form-urlencoded
      description: Create a new application.
      operationId: POST_applications
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/applicationRequest'
      produces:
        - application/json
      responses:
        '201':
          description: ''
          examples:
            application/json:
              app_id: ab3eud2
              shared_secret: 63f61863-4a51-4f6b-86e1-46edebcf9356
          schema:
            allOf:
              - properties:
                  app_id:
                    type: string
                  private_key:
                    type: string
                type: object
      summary: Create Application
      tags:
        - Application
  '/applications/{app_uuid}':
    delete:
      description: Delete an existing application.
      operationId: DELETE_applications-app_uuid
      produces:
        - application/json
      responses:
        '204':
          description: ''
      summary: Delete Application
      tags:
        - Application
    get:
      description: |
        Get details of an existing application.
      operationId: GET_applications-app_uuid
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
      summary: Get Application
      tags:
        - Application
    parameters:
      - in: path
        name: app_uuid
        required: true
        type: string
    put:
      consumes:
        - application/x-www-form-urlencoded
      description: >-
        Modify an existing application (NOTE: whenever a PUT is performed, a new
        shared secret is created and returned).
      operationId: PUT_applications-app_uuid
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/applicationRequest'
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              app_id: ab3eud2
              shared_secret: 63f61863-4a51-4f6b-86e1-46edebcf9356
          schema:
            properties:
              app_id:
                type: string
              shared_secret:
                type: string
            type: object
      summary: Update Application
      tags:
        - Application
  '/applications/{app_uuid}/keys':
    parameters:
      - in: path
        name: app_uuid
        required: true
        type: string
    post:
      description: ''
      operationId: POST_npa-applications-app_uuid-keys
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
      summary: Add Application Key
      tags:
        - Application
        - Npa
  '/applications/{app_uuid}/keys/{key_id}':
    get:
      description: ''
      operationId: GET_npa-applications-app_uuid-keys-key_id
      produces:
        - application/json
      responses:
        '200':
          description: ''
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
      summary: Get Application Key
      tags:
        - Application
        - Npa
    parameters:
      - in: path
        name: app_uuid
        required: true
        type: string
      - in: path
        name: key_id
        required: true
        type: string

definitions:
  applicationRequest:
    example:
      answer_method: GET
      answer_url: 'http://myanswerurl.com'
      application_type: voice
      backup_method: GET
      backup_url: 'http://mybackupurll.com'
      event_method: GET
      event_url: 'http://myeventurl.com'
      name: Nexmo-conference
      numberpool_id: '10'
    properties:
      answer_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      answer_url:
        description: URL that gets called once a call is answered. The URL returns a NCCO.
        type: string
      application_type:
        description: Type of application.
        enum:
          - voice
        type: string
      backup_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      backup_url:
        description: Backup event URL in case primary is unavailable.
        type: string
      event_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      event_url:
        description: Asynchronous webhook that receives event information of a call.
        type: string
      name:
        description: Friendly name of application.
        type: string
      numberpool_id:
        description: ID of number pool connected to the application.
        type: string
    required:
      - name
      - answer_url
      - event_url
      - application_type
    type: object
  applicationResponse:
    allOf:
      - $ref: '#/definitions/applicationRequest'
      - properties:
          _links:
            properties:
              numberpool:
                properties:
                  href:
                    type: string
                type: object
              self:
                properties:
                  href:
                    type: string
                type: object
            type: object
          application_id:
            type: string
        type: object
    example:
      _links:
        numberpool:
          href: /numberpools/10
        self:
          href: /applications/63f61863-4a51-4f6b-86e1-46edebcf9356
      answer_method: GET
      answer_url: 'http://myanswerurl.com'
      application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
      application_type: voice
      backup_method: GET
      backup_url: 'http://mybackupurll.com'
      event_method: GET
      event_url: 'http://myeventurl.com'
      name: Nexmo-conference
      numberpool_id: '10'
