swagger: '2.0'
info:
  version: '2.0'
  title: "Nexmo Application API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  /applications:
    get:
      summary: List and Filter Applications
      description: >  
        Returns a collection of the account's applications.
      tags:
        - Application
      parameters:
        - $ref: "../common/hal.yaml#/parameters/page_size"
        - $ref: "../common/hal.yaml#/parameters/page_offset"
      produces:
        - application/json
      responses:
        '200':
          description: Application Collection
          schema:
            allOf:
              - $ref: "../common/hal.yaml#/definitions/collection"
              - $ref: "../common/hal.yaml#/definitions/paging"
              - type: object
                properties:
                  _embedded:
                    properties:
                      applications:
                        items:
                          $ref: '#/definitions/applicationResponse'
                        type: array
                    type: object
          examples:
            application/json:
              _embedded:
                applications:
                  - _links:
                      numberpool:
                        href: /numberpools/10
                      self:
                        href: /applications/63f61863-4a51-4f6b-86e1-46edebcf9356
                    answer_method: GET
                    answer_url: 'http://myanswerurl.com'
                    application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
                    application_type: voice
                    backup_method: GET
                    backup_url: 'http://mybackupurll.com'
                    event_method: GET
                    event_url: 'http://myeventurl.com'
                    name: Nexmo-conference
                    numberpool_id: '10'
              _links:
                first:
                  href: /applications
                last:
                  href: /applications?page_offset=50
                next:
                  href: /applications?page_offset=20
                prev:
                  href: /applications
                self:
                  href: /applications?page_offset=10
              count: '1020'
              page_offset: '150'
              page_size: '50'
    post:
      summary: Create Application
      description: >
        Create a new application. Currently only a voice application is supported.
      tags:
        - Application
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/applicationRequest'
      responses:
        '201':
          description: Application Resource
          schema:
            allOf:
              - properties:
                  app_id:
                    type: string
                  private_key:
                    type: string
                type: object
          examples:
            application/json:
              app_id: ab3eud2
              shared_secret: 63f61863-4a51-4f6b-86e1-46edebcf9356

  '/applications/{app_uuid}':
    parameters:
      - $ref: "#/parameters/app_uuid"
    get:
      summary: Get Application
      description: >
        Get details of an existing application.
      tags:
        - Application
      produces:
        - application/json
      responses:
        '200':
          description: Application Resource
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'
    put:
      summary: Update Application
      description: >
        Modify an existing application.
      tags:
        - Application
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/applicationRequest'
      responses:
        '200':
          description: Application Resource
          schema:
            properties:
              app_id:
                type: string
              shared_secret:
                type: string
            type: object
          examples:
            application/json:
              app_id: ab3eud2
              shared_secret: 63f61863-4a51-4f6b-86e1-46edebcf9356
    delete:
      summary: Delete Application
      description: >
        Delete an exsisting appllication.
      tags:
        - Application
      produces: []
      responses:
        '204':
          description: No Content

  '/applications/{app_uuid}/keys':
    parameters:
      - $ref: "#/parameters/app_uuid"
    post:
      summary: Add Public Key
      description: >
        Upload and associate a public key with an application.
      tags:
        - Application
      produces:
        - application/json
      responses:
        '200':
          description: Application Resource
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'

  '/applications/{app_uuid}/keys/{key_id}':
    parameters:
      - $ref: "#/parameters/app_uuid"
      - in: path
        name: key_id
        required: true
        type: string
    get:
      summary: Get Application Public Key
      tags:
        - Application
      description: >
        Get a public key associated with the application.
      produces:
        - application/json
      responses:
        '200':
          description: Application Response
          schema:
            allOf:
              - $ref: '#/definitions/applicationResponse'
          examples:
            application/json:
              answer_method: GET
              answer_url: 'http://myanswerurl.com'
              application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
              application_type: voice
              backup_method: GET
              backup_url: 'http://mybackupurll.com'
              event_method: GET
              event_url: 'http://myeventurl.com'
              name: Nexmo-conference
              numberpool_id: '10'

definitions:
  applicationRequest:
    type: object
    required:
      - name
      - answer_url
      - event_url
      - application_type
    properties:
      answer_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      answer_url:
        description: URL that gets called once a call is answered. The URL returns a NCCO.
        type: string
      application_type:
        description: Type of application.
        enum:
          - voice
        type: string
      backup_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      backup_url:
        description: Backup event URL in case primary is unavailable.
        type: string
      event_method:
        default: POST
        description: HTTP method that is used to make the request. Defaults to POST.
        type: string
      event_url:
        description: Asynchronous webhook that receives event information of a call.
        type: string
      name:
        description: Friendly name of application.
        type: string
      numberpool_id:
        description: ID of number pool connected to the application.
        type: string
    example:
      answer_method: GET
      answer_url: 'http://myanswerurl.com'
      application_type: voice
      backup_method: GET
      backup_url: 'http://mybackupurll.com'
      event_method: GET
      event_url: 'http://myeventurl.com'
      name: Nexmo-conference
      numberpool_id: '10'

  applicationResponse:
    allOf:
      - $ref: '#/definitions/applicationRequest'
      - $ref: '../common/hal.yaml#/definitions/self'
      - type: object
        properties:
          application_id:
            type: string
          _links:
            type: object
            properties:
              numberpool:
                $ref: '../common/hal.yaml#/definitions/link'
    example:
      _links:
        numberpool:
          href: /numberpools/10
        self:
          href: /applications/63f61863-4a51-4f6b-86e1-46edebcf9356
      answer_method: GET
      answer_url: 'http://myanswerurl.com'
      application_id: 63f61863-4a51-4f6b-86e1-46edebcf9356
      application_type: voice
      backup_method: GET
      backup_url: 'http://mybackupurll.com'
      event_method: GET
      event_url: 'http://myeventurl.com'
      name: Nexmo-conference
      numberpool_id: '10'

parameters:
  app_uuid:
    description: Unique Application Identifier 
    in: path
    name: app_uuid
    required: true
    type: string