swagger: '2.0'
info:
  version: '1'
  title: "Nexmo Account API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  '/accounts/{account_id}':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: "Provide access to:\r\n- API Keys / Global Callbacks\r\n- Default HTTP Method\r\n- Throttling / Features / Etc\r\n- (future) Currency Preference"
      operationId: GET_account
      responses:
        default:
          description: ''
      summary: Get Account Settings
      tags:
        - Account
    put:
      consumes:
        - application/json
      description: ''
      operationId: PUT_account
      responses:
        default:
          description: ''
      summary: Update Account
      tags:
        - Account

  '/accounts/{account_id}/alerts':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: Create an alert to a phone / email / url based on alert criteria.
      operationId: get_alerts
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            allOf:
              - properties:
                  _embedded:
                    properties:
                      alerts:
                        items: {}
                        type: array
                    type: object
                type: object
              - $ref: '../common/hal.yaml#/definitions/paging'
      summary: Search / List Account Alerts
      tags:
        - Alerts
    post:
      consumes:
        - application/json
      description: Create an alert to a phone / email / url based on alert criteria.
      operationId: create_alert
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/alert-endpoint'
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/alert-endpoint'
      summary: Create Account Alert
      tags:
        - Alerts

  '/accounts/{account_id}/alerts/{id}':
    parameters:
      - $ref: "#/parameters/account_id"
      - in: path
        name: id
        required: true
        type: string
    get:
      consumes:
        - application/json
      description: ''
      operationId: get_alert
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/alert-endpoint'
      summary: Get Account Alert
      tags:
        - Alerts
    put:
      consumes:
        - application/json
      description: ''
      operationId: update_alert
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/alert-endpoint'
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/alert-endpoint'
      summary: Update Account Alert
      tags:
        - Alerts

  '/accounts/{account_id}/autoreload':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_payment
      parameters:
        - description: 'Filter by Payment Method ID '
          in: query
          name: method
          type: string
      responses:
        default:
          description: ''
      summary: Get Payment Configuration
      tags:
        - Payment
    put:
      consumes:
        - application/json
      description: ''
      operationId: PUT_payment
      parameters:
        - in: body
          name: body
          schema:
            properties:
              amount:
                description: Amount t AutoPay
                type: integer
              auto:
                description: Enable / Disable Auto Payments
                type: boolean
              method:
                description: Payment Method ID
                type: string
              threshold:
                description: Balance Threshold to Reload
                type: integer
            required:
              - auto
            type: object
      responses:
        default:
          description: ''
      summary: Get Payment Configuration
      tags:
        - Payment

  '/accounts/{account_id}/balance':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: get-balance
      parameters:
        - default: EUR
          enum:
            - EUR
            - USD
          in: query
          name: currency
          type: string
      responses:
        default:
          description: ''
      summary: Get Balance
      tags:
        - Account

  '/accounts/{account_id}/instruments':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_payment-methods
      responses:
        default:
          description: ''
      summary: Search / List Payment Methods
      tags:
        - Payment

  '/accounts/{account_id}/instruments/{id}':
    parameters:
      - $ref: "#/parameters/account_id"
      - in: path
        name: id
        required: true
        type: string
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_payment-methods-id
      responses:
        default:
          description: ''
      summary: Get Payment Method Details
      tags:
        - Payment

  '/accounts/{account_id}/secondaries':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_account-secondaries
      responses:
        default:
          description: ''
      summary: List Secondary Accounts
      tags:
        - Account

  '/accounts/{account_id}/transactions':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_payment-transactions
      responses:
        default:
          description: ''
      summary: Search / List Past Payments
      tags:
        - Payment

  '/accounts/{account_id}/transactions/':
    parameters:
      - $ref: "#/parameters/account_id"
    post:
      consumes:
        - application/json
      description: ''
      operationId: POST_payment-transactions
      responses:
        default:
          description: ''
      summary: Make Payment
      tags:
        - Payment

  '/accounts/{account_id}/transactions/{id}':
    parameters:
      - $ref: "#/parameters/account_id"
      - in: path
        name: id
        required: true
        type: string
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_payment-transactions-id
      responses:
        default:
          description: ''
      summary: Get Payment Details
      tags:
        - Payment

  '/accounts/{account_id}/users':
    parameters:
      - $ref: "#/parameters/account_id"
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_users
      responses:
        default:
          description: ''
      summary: Search / List Users
      tags:
        - Users
    post:
      consumes:
        - application/json
      description: ''
      operationId: POST_users
      responses:
        default:
          description: ''
      summary: Create User
      tags:
        - Users

  '/accounts/{account_id}/users/{id}':
    get:
      consumes:
        - application/json
      description: ''
      operationId: GET_users-id
      responses:
        default:
          description: ''
      summary: Get User Details
      tags:
        - Users
    parameters:
      - $ref: "#/parameters/account_id"
      - in: path
        name: id
        required: true
        type: string
    put:
      consumes:
        - application/json
      description: ''
      operationId: PUT_users-id
      responses:
        default:
          description: ''
      summary: Update User Details
      tags:
        - Users

definitions:
  alert-endpoint:
    properties:
      endpoint:
        type: string
      type:
        enum:
          - email
          - webhook
          - phone
        type: string
    required:
      - type
      - endpoint
    type: object

parameters:
  account_id:
    description: Account Identifier 
    name: account_id
    in: path
    required: true
    type: string