swagger: '2.0'
info:
  version: '1'
  title: "Nexmo Application API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  /users:
    get:
      summary: List and Filter Users
      description: > 
        Returns a collection of the application's users.
      tags:
        - Users
      produces:
      - application/json
      parameters:
        - name: name
          in: query
          type: string
          required: false
      responses:
        '200':
          description: Application Collection
          schema:
            $ref: "#/definitions/collection"
    post:
      summary: Create User
      description: >
        Create a new user, used by the conversation API and the message API.
      tags:
        - Users
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/resource'
      responses:
        '200':
          description: User Resource
          schema:
            $ref: '#/definitions/resource'

  /users/{user_id}:
    parameters:
      - $ref: "#/parameters/user_id"    
    get:
      summary: Get User
      description: >
        Get details of an exsisting user.
      tags:
        - Users
      produces:
      - application/json
      responses:
        '200':
          description: A user
          schema:
            $ref: '#/definitions/resource'
    put:
      summary: Update User
      description: > 
        Modify an exsisting user.
      tags:
        - Users
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/resource'
      responses:
        '200':
          description: A user
          schema:
            $ref: '#/definitions/resource'
    delete:
      summary: Delete User
      description: >
        Delete a exsisting user.
      tags: 
        - User
      produces:
      - application/json
      responses:
        '204':
          description: No Content

definitions:
  collection:
    type: object
    allOf:
      - $ref: "../common/hal.yaml#/definitions/collection"
      - $ref: "../common/hal.yaml#/definitions/paging"
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              users:
                type: array
                items:
                  $ref: '#/definitions/resource'
    
  resource:
    allOf:
    - $ref: '../common/hal.yaml#/definitions/self'
    - type: object
      properties:
        uuid:
          description: ID of the corresponding User
          type: string
        name:
          description: The unique name for this User
          type: string
        display_name:
          description: The full name to be displayed to end users
          type: string
        image_url:
          description: A URL for an image representing this user
          type: string
        channels:
          type: object
        
parameters:
  user_id:
    name: user_id
    in: path
    description: User ID
    required: true
    type: string