swagger: '2.0'
info:
  version: '1'
  title: "Nexmo Message API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  '/messages':
    get:
      summary: List and Filter Messages
      description: >
        Returns a collection of the message resources.
      tags:
        - Messages
      parameters:
        - $ref: "../common/hal.yaml#/parameters/page_size"
        - $ref: "../common/hal.yaml#/parameters/page_offset"
      produces:
        - application/json
      responses:
        200:
          description: Message Collection
          schema:
            $ref: '#/definitions/collection'
    post:
      summary: Send A Message
      description: >
        Create a message to be delivered over carrier or app networks.
      tags:
        - Messages
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/resource'
      responses:
        201:
          description: Message Resource
          schema:
            $ref: '#/definitions/resource'

  '/messages/{message_uuid}':
    parameters:
      - $ref: "#/parameters/message_uuid"
    get:
      summary: Get Message
      description: >
        Get log of a sent or recieved message.
      tags:
        - Messages
      consumes:
        - application/json
      responses:
        200:
          description: Message Resource
          schema:
            $ref: '#/definitions/resource'

  '/messages/{message_uuid}/conversion':
    parameters:
      - $ref: "#/parameters/message_uuid"
    get:
      summary: Report Message Conversion
      description: >
        Get the conversion report for this message.
      tags:
        - Messages
        - Conversions
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/conversion'
      responses:
        200:
          description: Conversion Resource
          schema:
            $ref: '#/definitions/conversion'
        400:
          description: Conversion Not Found
    put:
      summary: Report Message Conversion
      description: >
        Create a conversion report for a sent message. This can only be done once.
      tags:
        - Messages
        - Conversions
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Conversion Resource
          schema:
            $ref: '#/definitions/conversion'

definitions:
  conversion:
    description: Report of conversion.
    type: object
    properties:
      delivered: 
        description: >
          `true` if the message was delivered.
        type: boolean
      timestamp:
        description: >
          The time the message was converted in RFC3339's date-time format. 
        type: string
        format: date-time

  addressable:
    description: Representation of an addressable entity.
    type: object
    properties:
      type:
        description: Type of entity.
        type: string
        enum:
          - mobile
          - facebook
          - wechat
          - viber
      itentifier:
        description: >
          The address or identifier for this entity. 

  resource:
    description: >
      Representation of a message (inbound or outbound), returned from API and used as the payload for message webhooks.
    type: object
    required:
      - to
      - from
      - message
      - message_id
      - direction
      - status
      - created
      - usage
      - network
    properties:
      message_id:
        description: Message Identifier 
        type: string
        format: uuid
        readOnly: true
      to: 
        $ref: "#/definitions/addressable"
      from: 
        $ref: "#/definitions/addressable"
      message: 
        description: >
          Message to deliver. At least one property is requred. `text` sends a simple message, if sending rich content by `url` a `text` description is required. `media` may only be used on its own. If a custom `content` is sent the `type` must also be sent.
        type: object
        properties:
          text: 
            description: Message body or description of content.
            type: string
          url:
            description: Location of the content.
            type: string
            format: url
          media: 
            description: Binary content, base64 encoded
            type: string
            format: byte
          type:
            description: Name of custom type.
            type: string
          content:
            description: JSON message structure.
            type: string
          
      direction:
        description: Indicates if the message was inbound or outbound.
        type: string
        enum:
          - inbound
          - outbound
        readOnly: true
      status:
        description: Current status of message.
        type: string
        enum: 
          - delivered
          - expired
          - failed
          - rejected
          - accepted
          - bufferend
          - unknown
        readOnly: true
      created:
        description: Timestamp message was created.
        type: string
        format: date-type
        readOnly: true
      delivered:
        description: Timestamp message was delivered.
        type: string
        format: date-type
        readOnly: true
      usage:
        description: Usage of balance or quota incurred for this message.
        type: object
        readOnly: true
        properties:
          currency:
            description: The currency of the usage cost.
            type: string
          amount:
            description: The usage amount.
            type: string
      network:
        description: Identifier of the network delivering the message.
        type: object
        readOnly: true
        properties:
          type: 
            description: Type of entity.
            type: string
            enum:
              - mobile
              - facebook
              - wechat
              - viber
          itentifier:
            description: >
              The address or identifier for the network. 
      _embedded:
        description: Embedded Resources
        type: object
        readOnly: true
        properties:
          conversion:
            $ref: "#/definitions/conversion"
      _links:
        $ref: "../common/hal.yaml#/definitions/collection"

  collection:
    description: >
      Collection of messasge resources.
    allOf:
      - $ref: "../common/hal.yaml#/definitions/paging"
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              messagess:
                type: array
                items:
                  $ref: '#/definitions/resource'
          _links:
            $ref: "../common/hal.yaml#/definitions/collection"

parameters:
  message_uuid:
    name: message_uuid
    in: path
    required: true
    type: string
