openapi: "3.0.0"
info:
  version: 1.0.0
  title: Nexmo Audit API
  description: >
    Nexmo's Audit API allows you to view details of changes to your account.
  contact:
    name: Nexmo.com
    email: devrel@nexmo.com
    url: 'https://developer.nexmo.com/'
    x-twitter: Nexmo
  termsOfService: 'https://www.nexmo.com/terms-of-use'
  license:
    name: The MIT License (MIT)
    url: 'https://opensource.org/licenses/MIT'
  x-logo:
    url: 'https://twitter.com/Nexmo/profile_image?size=original'
  x-apiClientRegistration: 'https://dashboard.nexmo.com/sign-up'
servers:
  - url: https://api.nexmo.com
paths:
  '/beta/audit/events':
    get:
      summary: Retrieve audit events
      description:
      parameters:
        - name: api_key
          description: Your API key
          required: true
          in: query
          example: abcd1234
          schema:
            type: string
            minLength: 8
            maxLength: 8
        - name: api_secret
          description: Your API secret.
          required: true
          in: query
          example: abcdef0123456789
          schema:
            type: string
            minLength: 16
            maxLength: 16
          # TODO: confirm whether sig works in PROD. if it does, add in sig
          # and remove required: true on api_secret
