---
openapi: 3.0.0
info:
  version: 1.10.1
  title: Account API
  description: Retrieve information about accounts.
  contact:
    name: "Account API"
    url: "https://businesssupport.vonage.com/contactus"
  license:
    name: "Vonage"
    url: "https://www.vonage.com/business/legal-policy-center/business-cloud/tos"

servers:
- url: "https://api.vonage.com"  
paths:

  "/api/accounts/{account_id}":
    get:
      operationId: AccountCtrl.getAccountServicesByAccountID
      parameters:
        - $ref: "#/components/parameters/AccountID"
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/AccountHalResponse"
        "404":
          description: Account not found
      security:
        - LoginName:
            []
      summary: Get account data by ID

  "/api/accounts/{account_id}/locations":
    get:
      operationId: AccountCtrl.getLocationsByAccountID
      parameters:
        - $ref: "#/components/parameters/AccountID"
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/LocationsHalResponse"
      security:
        - LoginName:
            []
      summary: Get account locations data by account ID

  "/api/accounts/{account_id}/locations/{location_id}":
    get:
      operationId: AccountCtrl.getLocationByID
      parameters:
        - $ref: "#/components/parameters/AccountID"
        - in: path
          name: location_id
          required: true
          schema:
            type: number
          description: The location ID
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/LocationHalResponse"
        "404":
          description: Location not found
      security:
        - LoginName:
            []
      summary: Get location data by account ID and location ID

components:
  securitySchemes:
    LoginName:
      type: apiKey
      name: x-von-user
      in: header

  parameters:
    AccountID:
      in: path
      name: account_id
      required: true
      schema:
        type: string
      description: The account ID

  schemas:
    Href:
      properties:
        href:
          type: string
    Links:
      properties:
        first:
          $ref: "#/components/schemas/Href"
        prev:       
          $ref: "#/components/schemas/Href"
        self:       
          $ref: "#/components/schemas/Href"
        next:       
          $ref: "#/components/schemas/Href"
      type: object

    Address:
      properties:
        address_1:
          type: string
        address_2:
          type: string
        country:
          type: string
        state:
          type: string
        city:
          type: string
        postal_code:
          type: string
      type: object

    Account:
      properties:
        id:
          type: number
        name:
          type: string
        status:
          type: string
        address:
          $ref: "#/components/schemas/Address"
      type: object

    AccountEmbeddedObject:
      properties:
        data:
          $ref: "#/components/schemas/Account"
      type: object

    AddressWithTimeZone:
      properties:
        address_1:
          type: string
        address_2:
          type: string
        country:
          type: string
        state:
          type: string
        city:
          type: string
        postal_code:
          type: string
        time_zone:
          type: string
      type: object

    Location:
      properties:
        id:
          type: number
        name:
          type: string
        address:
          $ref: "#/components/schemas/AddressWithTimeZone"
      type: object
    
    LocationsEmbeddedObject:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Location"
          type: array
      type: object

    LocationEmbeddedObject:
      properties:
        data:
          $ref: "#/components/schemas/Location"
      type: object

    AccountHalResponse:
      type: object
      properties:
        page_size:         
          type: number
        cursor:                  
          type: number
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/AccountEmbeddedObject"        
    LocationHalResponse:
      description: Data for the specific location
      properties:
        page_size:
          type: number          
        cursor:
          type: number          
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/LocationEmbeddedObject"
      type: object
    LocationsHalResponse:
      description: Data for all associated locations
      properties:
        page_size:
          type: number         
        cursor:
          type: number          
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/LocationsEmbeddedObject"
      type: object

  