---
openapi: 3.0.0
info:
  version: 1.10.1
  title: Extension API
  description: Retrieve information about extensions.
  contact:
    name: "Extension API"
    url: "https://businesssupport.vonage.com/contactus"
  license:
    name: "Vonage"
    url: "https://www.vonage.com/business/legal-policy-center/business-cloud/tos"

servers:
- url: "https://api.vonage.com"  
paths:

  "/api/accounts/{account_id}/extensions":
    get:
      operationId: ExtensionCtrl.getAccountExtensions
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - in: query
          name: page_size
          required: false
          schema:
            type: number
          description: Page size for pagination
        - in: query
          name: cursor
          required: false
          schema:
            type: number
          description: Cursor for pagination
        - in: query
          name: order
          required: false
          schema:
            type: string
          description: Sort results in ascending (ASC) or descending (DESC) order
        - in: query
          name: location_id
          required: false
          schema:
            type: number
          description: filter by location id
        - in: query
          name: phone_number
          required: false
          schema:
            type: string
          description: filter by phone number
        - in: query
          name: login_name
          required: false
          schema:
            type: string
          description: filter by login name
        - in: query
          name: email
          required: false
          schema:
            type: string
          description: filter by email address
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EndUserRouteHalResponse"
        "404":
          description: Extension not found
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - LoginName:
            []
      summary: Get account extensions data by account ID

  "/api/accounts/{account_id}/extensions/{extension_number}":
    get:
      operationId: ExtensionCtrl.getAccountExtensionByID
      tags:
        - Extensions
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - in: path
          name: extension_number
          required: true
          schema:
            type: string
          description: The extension number
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/EndUserRouteHalResponse"
        "404":
          description: Extension not found
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      security:
        - LoginName:
            []
      summary: Get extension data by account ID and extension number

components:
  securitySchemes:
    LoginName:
      type: apiKey
      name: x-von-user
      in: header

  parameters:
    AccountID:
      in: path
      name: account_id
      required: true
      schema:
        type: string
      description: The account ID
  
  schemas:
    Href:
      properties:
        href:
          type: string
      type: object

    Links:
      properties:
        first:
          $ref: "#/components/schemas/Href"
        prev:
          $ref: "#/components/schemas/Href"
        self:
          $ref: "#/components/schemas/Href"
        next:
          $ref: "#/components/schemas/Href"
      type: object

    BasicUser:
      properties:
        email:
          type: string
        login_name:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      type: object

    DID:
      properties:
        phone_number:
          type: string
        custom_tag:
          type: string
      type: object

    Line:
      properties:
        handset_name:
          type: string
        sip_id:
          type: string
      type: object

    EndUserRoute:
      properties:
        extension_number:
          type: string
        user:
          $ref: "#/components/schemas/BasicUser"
        location_id:
          type: number
        vtt_enabled:
          type: boolean
        dnd_enabled:
          type: boolean
        caller_id:
          type: string
        block_caller_id:
          type: boolean
        dids:
          items:
            $ref: "#/components/schemas/DID"
          type: array
        extension_handsets:
          items:
            $ref: "#/components/schemas/Line"
          type: array
      type: object

    EndUserRouteEmbeddedObject:
      properties:
        data:
          $ref: "#/components/schemas/EndUserRoute"
      type: object

    EndUserRouteHalResponse:
      properties:
        page_size:
          type: number
        cursor:
          type: number
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/EndUserRouteEmbeddedObject"
      type: object

    ErrorResponse:
      properties:
        msg:
          description: Error message
          type: string
        status:
          description: Http Response Code
          type: number
      type: object


