---
openapi: 3.0.0
info:
  version: 1.10.1
  title: User API
  description: Retrieve information about users
  termsOfService: ""
servers:
- url: "https://api.vonage.com"  
paths:

  "/api/accounts/{account_id}/users":
    get:
      operationId: UserCtrl.getUsers
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - in: query
          name: page_size
          required: false
          schema:
            type: number
        - in: query
          name: cursor
          required: false
          schema:
            type: number
        - description: ASC or DESC
          in: query
          name: order
          required: false
          schema:
            type: string
        - description: filter by first name
          in: query
          name: first_name
          required: false
          schema:
            type: string
        - description: filter by last name
          in: query
          name: last_name
          required: false
          schema:
            type: string
        - description: filter by login name
          in: query
          name: login_name
          required: false
          schema:
            type: string
        - description: filter by email address
          in: query
          name: email
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/responses/UsersHalResponse"
      security:
        - LoginName:
            []
      summary: Get account users data by account ID

  "/api/accounts/{account_id}/users/{user_id}":
    get:
      operationId: UserCtrl.getUserByID
      parameters:
        - $ref: '#/components/parameters/AccountID'
        - in: path
          name: user_id
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/responses/UserHalResponse"
        "404":
          description: User not found
      security:
        - LoginName:
            []
      summary: Get user data by account ID and user ID
components:
  securitySchemes:
    LoginName:
      type: apiKey
      name: x-von-user
      in: header

  parameters:
    AccountID:
      in: path
      name: account_id
      required: true
      schema:
        type: string

  responses:
    UserHalResponse:
      properties:
        page_size:
          type: number
        cursor:
          type: number
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/UserEmbeddedObject"
      type: object

    UsersHalResponse:
      properties:
        page_size:
          type: number
        cursor:
          type: number
        _links:
          $ref: "#/components/schemas/Links"
        _embedded:
          $ref: "#/components/schemas/UsersEmbeddedObject"
      type: object

  schemas:
    Href:
      properties:
        href:
          type: string
      type: object

    Links:
      properties:
        first:
          $ref: "#/components/schemas/Href"
        prev:
          $ref: "#/components/schemas/Href"
        self:
          $ref: "#/components/schemas/Href"
        next:
          $ref: "#/components/schemas/Href"
      type: object

    Contact:
      properties:
        type:
          type: string
        value:
          type: string
      type: object

    UserExtension:
      properties:
        dids:
          items:
            type: string
          type: array
        extension_number:
          type: string
      type: object

    User:
      properties:
        email:
          type: string
        login_name:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: number
        contact_numbers:
          items:
            $ref: "#/components/schemas/Contact"
          type: array
        extensions:
          items:
            $ref: "#/components/schemas/UserExtension"
          type: array
      type: object

    UsersEmbeddedObject:
      properties:
        data:
          items:
            $ref: "#/components/schemas/User"
          type: array
      type: object

    UserEmbeddedObject:
      properties:
        data:
          $ref: "#/components/schemas/User"
      type: object