swagger: '2.0'
info:
  version: '1'
  title: "Nexmo Pool API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  /pools:
    get:
      description: ''
      operationId: GET_npa-pools
      produces:
        - application/json
      responses:
        default:
          description: ''
      summary: Search / List Pools
      tags:
        - Numbers

  '/pools/{pool_id}':
    get:
      description: ''
      operationId: GET_npa-pools-pool_id
      produces:
        - application/json
      responses:
        default:
          description: ''
      summary: Get Pool Details
      tags:
        - Numbers
    parameters:
      - in: path
        name: pool_id
        required: true
        type: string
    put:
      description: Point to application.
      operationId: PUT_npa-pools-pool_id
      produces:
        - application/json
      responses:
        default:
          description: ''
      summary: Update Pool
      tags:
        - Numbers

  '/pools/{pool_id}/numbers':
    get:
      description: List Numbers
      operationId: GET_npa-pools-pool_id-numbers
      produces:
        - application/json
      responses:
        default:
          description: ''
      summary: Search / List Pool Numbers
      tags:
        - Numbers
    parameters:
      - in: path
        name: pool_id
        required: true
        type: string
