swagger: '2.0'
info:
  version: '1'
  title: "Nexmo Conversation API"
securityDefinitions:
  $ref: ../api-spec.yaml#/securityDefinitions

paths:
  /conversations:
    get:
      summary: List and Filter Conversations
      description: >
        Returns a collection of the application's conversations.
      tags:
        - Conversations
      produces:
      - application/json
      parameters:
        - $ref: "#/parameters/filter_user"
        - name: name
          in: query
          type: string
          required: false
      responses:
        '200':
          description: Conversation Collection
          schema:
            type: array
            items:
              $ref: '#/definitions/conversation_collection'
    post:
      summary: Create Conversation
      description: >
        Create a conversation.
      tags:
        - Conversations
      consumes:
       - application/json
      produces:
       - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/conversation'
      responses:
        '201':
          description: Conversation Resource
          schema:
            $ref: '#/definitions/conversation'

  /conversations/{conversation_id}:
    parameters:
      - $ref: "#/parameters/conversation_id"
    get:
      summary: Get a Conversation
      description: > 
        Returns a specific conversation.
      tags:
        - Conversations
      produces:
      - application/json
      responses:
        '200':
          description: Conversation Resource
          schema:
            $ref: '#/definitions/conversation'
    put:
      summary:  Update a Conversation
      description: >
        Udpate a specific conversation.
      tags:
        - Conversations
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/conversation'
      responses:
        '200':
          description: An updated conversation
          schema:
            $ref: '#/definitions/conversation'
    delete:
      summary:  Delete a Conversation
      description: >
        Delete a specific conversation.
      tags:
        - Conversations
      produces: []
      responses:
        '204':
          description: No Content

  /conversations/{conversation_id}/members:
    parameters:
      - $ref: "#/parameters/conversation_id"
    post:
      summary:  Add a Member
      description: >
        Invite or join a member to a conversation.
      tags:
        - Conversations
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: action
          in: query
          required: true
          type: string
          enum: [invite, join]
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/member'
      responses:
        '201':
          description: Member Resource
          schema:
            $ref: '#/definitions/member'
    get:
      summary:  List and Filter Members
      description: >
        Returns a collection of the conversation's members.
      tags:
        - Conversations
      produces:
      - application/json
      parameters:
        - $ref: "../common/hal.yaml#/parameters/page_size"
        - $ref: "../common/hal.yaml#/parameters/since"
        - $ref: "../common/hal.yaml#/parameters/until"
        - name: state
          in: query
          description: The member state
          required: false
          type: string
          enum: [knocking, invited, joined, left]
        - name: channel
          in: query
          description: The channel type (pstn, app, sms)
          required: false
          type: string
        - name: count
          in: query
          description: Only return the record count
          required: false
          type: integer
      responses:
        '200':
          description: Member Collection
          schema:
            $ref: '#/definitions/member_collection'

  /conversations/{conversation_id}/members/{member_id}:
    parameters:
      - $ref: "#/parameters/conversation_id"
      - $ref: "#/parameters/member_id"
    get:
      summary: Get a Member
      description: >
        Returns a specfic member resource.
      tags:
        - Conversations
      produces:
      - application/json
      responses:
        '200':
          description: Member Resource
          schema:
            $ref: '#/definitions/member'
    put:
      summary: Update a Member
      description: >
        Update a specfic member resource.
      tags:
        - Conversations
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: action
          in: query
          required: true
          type: string
          enum: [join]
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/member'
      responses:
        '200':
          description: Member Collection
          schema:
            $ref: '#/definitions/member'
    delete:
      summary: Delete a Member
      description: >
        Delete a specfic member resource.
      tags:
        - Conversations
      produces: []
      responses:
        '204':
          description: No Content

  /conversations/{conversation_id}/events:
    parameters:
      - $ref: "#/parameters/conversation_id"
    post:
      summary: Create Conversation Event
      description: >
        Add an event to the conversation.
      tags:
        - Conversations
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/event'
      responses:
        '201':
          description: Event Resource
          schema:
            $ref: '#/definitions/event'
    get:
      summary: List and Filter Conversation Events
      description: >
        Returns a collection of the conversation's events.
      tags:
        - Conversations
      produces:
      - application/json
      parameters:
        - $ref: "../common/hal.yaml#/parameters/page_size"
        - $ref: "../common/hal.yaml#/parameters/since"
        - $ref: "../common/hal.yaml#/parameters/until"
      responses:
        '200':
          description: Event Collection
          schema:
            $ref: '#/definitions/event_collection'

  /conversations/{conversation_id}/events/{event_id}:
    parameters:
      - $ref: "#/parameters/conversation_id"
      - $ref: "#/parameters/event_id"
    get:
      summary: Get Event
      description: >
        Returns a specific event.
      tags:
        - Conversations
      produces:
      - application/json
      responses:
        '200':
          description: Event Resource
          schema:
            $ref: '#/definitions/event'
    delete:
      summary: Delete Event
      description: >
        Delete a specific event.
      tags:
        - Conversations
      produces:
      - application/json
      responses:
        '204':
          description: No Content

definitions:
  event_collection:
    type: object
    allOf:
      - $ref: "../common/hal.yaml#/definitions/collection"
      - $ref: "../common/hal.yaml#/definitions/cursor"
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              events:
                type: array
                items:
                  $ref: '#/definitions/event'

  event:
    allOf:
    - $ref: '../common/hal.yaml#/definitions/self'
    - type: object
      properties:
        id:
          type: integer
        type:
          type: string
        from:
          type: string
        to:
          type: string
        body:
          type: object
        timestamp:
          type: object
          description: ISO-8601 dates
          properties:
            created:
              type: string
              format: date-time
            deleted:
              type: string
              format: date-time

  conversation_collection:
    type: object
    allOf:
      - $ref: "../common/hal.yaml#/definitions/collection"
      - $ref: "../common/hal.yaml#/definitions/paging"
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              conversations:
                type: array
                items:
                  $ref: '#/definitions/conversation'

  conversation:
    allOf:
    - $ref: '../common/hal.yaml#/definitions/self'
    - type: object
      properties:
        uuid:
          type: string
          readOnly: true
        name:
          type: string
        sequence_number:
          description: The last event id in this conversation
          type: integer
          readOnly: true
        self_uuid:
          description: The member id of the requesting user (if any)
          readOnly: true
        display_name:
          type: string
        image_url:
          type: string
        properties:
          type: object
          description: Settings for the conversation
          properties:
            speaking_detection_level:
              type: string
        timestamp:
          type: object
          description: ISO-8601 dates
          properties:
            created:
              type: string
              format: date-time
            deleted:
              type: string
              format: date-time
        _embedded:
          type: object
          properties:
            members:
              type: array
              items:
                $ref: '#/definitions/member'

  member_collection:
    type: object
    allOf:
      - $ref: "../common/hal.yaml#/definitions/collection"
      - $ref: "../common/hal.yaml#/definitions/cursor"
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              members:
                type: array
                items:
                  $ref: '#/definitions/member'

  member:
    allOf:
    - type: object
      properties:
        uuid:
          type: string
          description: Member ID
        state:
          type: string
          description: State
          enum: [knocking, invited, joined, left]
        timestamp:
          type: object
          description: ISO-8601 dates
          properties:
            created:
              type: string
              format: date-time
            knocked:
              type: string
              format: date-time
            invited:
              type: string
              format: date-time
            joined:
              type: string
              format: date-time
            left:
              type: string
              format: date-time
        user:
          $ref: '../users/api-spec.yaml#/definitions/resource'
        channel:
          type: object
          properties:
            app:
              type: object
            pstn:
              type: object
              properties:
                id:
                  type: string
                  description: The Call ID
                from:
                  type: string
                to:
                  type: string
                direction:
                  type: string
                  description: Direction of call, outbound is from the conversation
                  enum: [inbound, outbound]
                network:
                  type: string
                rate:
                  type: string
                price:
                  type: string
                  description: Only available for a member in left state
            sip:
              type: object
            sms:
              type: object
        media:
          type: object
          properties:
            text:
              type: object
            audio:
              type: object
            video:
              type: object
              
parameters:
  filter_user:
    name: user_uuid
    in: query
    description: Restrict to conversations this user is a memebr of
    type: string
    required: false
  conversation_id:
    name: conversation_id
    in: path
    description: Conversation ID
    type: string
    required: true
  member_id:  
    name: member_id
    in: path
    description: Member ID
    required: true
    type: string
  event_id:
    name: event_id
    in: path
    description: Event ID
    required: true
    type: string
    
    
  